### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jiapeng407** [LydiaXiaohongLi/TriTraining#1]
I'm sorry to bother you, Recently I have been doing some experiments on this aspect, but I can't understand part of your code. Could you please share with me the source code (data set), I would be very grateful if you could help me.
I wish you every success in your career.Looking forward to your reply.

**Comment by LydiaXiaohongLi** [comment]
Hi, you can use the tritaining.py and selftraining.py in this repository for the source code of the tri training, tri training with disagreement and self training implementation. The dataset we used are the datasets used in original Tri training paper (as cited in ReadMe file). You can find them on UCI dataset website, e.g. the 'ionosphere' data set can be found at https://archive.ics.uci.edu/ml/datasets/ionosphere. Additionally, we have uploaded one of the data set 'australian' in australian.dat file in the repository. Let me know if this helps

**Comment by Jiapeng407** [comment]
> Hi, you can use the tritaining.py and selftraining.py in this repository for the source code of the tri training, tri training with disagreement and self training implementation. The dataset we used are the datasets used in original Tri training paper (as cited in ReadMe file). You can find them on UCI dataset website, e.g. the 'ionosphere' data set can be found at https://archive.ics.uci.edu/ml/datasets/ionosphere. Additionally, we have uploaded one of the data set 'australian' in australian.dat file in the repository. Let me know if this helps

Thank you very much for your reply, which is very useful to me.In fact, I've been looking at tri-training algorithms lately，But it always fails to achieve it well. Have you ever done the code of tri-training algorithm before?I'd really appreciate it if you could

**Comment by LydiaXiaohongLi** [comment]
Hi, we didnt have very good results with Tri training algo too, even though we have been using the same data set as quoted in the original paper. And we found our implementation follows the algo as described in the paper too.
